[package]
version = "0.1.0"
name = "classifier-program"
edition = "2021"

[dependencies]
alloy-sol-types.workspace = true
classifier-io.workspace = true
classifier.workspace = true
sp1-zkvm = "1.1.0"

ndarray.workspace = true